[basic]
host = "my-hf-mirror.com"
port = 8090
ssl-key = ""
ssl-cert = ""
repos-path = "./repos"
cache-size-limit = ""
cache-clean-strategy = "LRU"
hf-scheme = "https"
hf-netloc = "huggingface.co"
hf-lfs-netloc = "cdn-lfs.huggingface.co"
mirror-scheme = "http"
mirror-netloc = "my-hf-mirror.com:8090"
mirror-lfs-netloc = "my-hf-mirror.com:8090"
mirrors-path = ["./mirrors_dir"]

[accessibility]
offline = false
